// The worker must carry tracer.py itself — SPEC.md forbids fetching it over the
// network. Rather than keep a hand-copied duplicate that drifts from /tracer,
// generate a TS module from the real Python sources at build time.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const tracerDir = join(here, '..', '..', 'tracer')
const out = join(here, '..', 'lib', 'pyodide', 'tracer-sources.generated.ts')

// cli.py is intentionally absent: it is argparse plumbing the worker never uses.
export const MODULES = ['__init__.py', 'limits.py', 'serialize.py', 'tracer.py', 'delta.py']

const entries = MODULES.map((name) => {
  const source = readFileSync(join(tracerDir, name), 'utf8')
  return `  ${JSON.stringify(name)}: ${JSON.stringify(source)},`
}).join('\n')

const file = `// GENERATED by scripts/inline-tracer.mjs — do not edit.
// Source of truth is /tracer/*.py at the repo root.

export const TRACER_SOURCES: Record<string, string> = {
${entries}
}

export const TRACER_MODULE_NAMES = Object.keys(TRACER_SOURCES)
`

writeFileSync(out, file)
console.log(`inline-tracer: ${MODULES.length} modules -> lib/pyodide/tracer-sources.generated.ts`)
